Bump to 1.0.6202
nedap/docker-datomic pull request #6
Opened 2020-09-15 13:37 UTC by Tim108

I heard the server was getting an upgrade to this version so it would be nice if we could also use this version in development.

2020-09-15 13:56 UTC, thumbnail approved these changes
> I added a tag to this commit, not sure where that went. Hopefully it will work when pushed to master.

There's no tag on the commit. without a commit it will not be built regardless of the branch. 

_however_ it's fine to create a release after merging this PR; which'll create a PR for you.


PR seems okay; let's await @Gluestick's approval,, as i'm not too familiar with this repo.

2020-09-16 07:09 UTC, Gluestick requested changes
The version scheme for this project was changed to `a.b.c.d` instead of `a.b.c` to allow bugfix/tweak releases for the same datomic version. I somehow missed the readme/bump script when I did that...

Would you mind changing those to incorporate an extra `.\d`? You could then push the tag `1.0.6202.0` once merged to master.

2020-09-16 07:09 UTC, Gluestick commented on README.md
> +    image: quay.io/nedap/datomic:1.0.6202
```suggestion
    image: quay.io/nedap/datomic:1.0.6202.0
```

2020-09-16 07:09 UTC, Gluestick commented on Dockerfile
> +ENV DATOMIC_VERSION 1.0.6202
```suggestion
ENV DATOMIC_VERSION 1.0.6202.0
```

2020-09-16 07:09 UTC, Gluestick commented on README.md
> +      - datomic-data:/opt/datomic-pro-1.0.6202/data
```suggestion
      - datomic-data:/opt/datomic-pro-1.0.6202.0/data
```

2020-09-16 07:09 UTC, Gluestick commented on bump.sh
> +sed -i '' -e "s/datomic-pro-[0-9]\.[0-9]\.[0-9]*/datomic-pro-$1/" README.md
```suggestion
sed -i '' -e "s/quay.io\/nedap\/datomic:[0-9]\.[0-9]\.[0-9]*\.[0-9]*/quay.io\/nedap\/datomic:$1/" README.md
sed -i '' -e "s/datomic-pro-[0-9]\.[0-9]\.[0-9]\.[0-9]**/datomic-pro-$1/" README.md
```

2020-09-16 07:43 UTC, Tim108 commented on Dockerfile
> +ENV DATOMIC_VERSION 1.0.6202
Wait, isn't it going to try to pull datomic version 1.0.6202.0 now? Which doesn't exist, because the .0 is only for this project?

2020-09-17 07:44 UTC, Gluestick commented on Dockerfile
> +ENV DATOMIC_VERSION 1.0.6202
Oops, good point, this one doesn't apply.

2020-09-17 07:45 UTC, Gluestick commented on Dockerfile
> +ENV DATOMIC_VERSION 1.0.6202.0
```suggestion
ENV DATOMIC_VERSION 1.0.6202
```

As mentioned this one actually doesn't need the 4th digit 😅

2020-09-17 07:56 UTC, Tim108 commented on Dockerfile
> +ENV DATOMIC_VERSION 1.0.6202.0
Then i think we should change the script to also make the script like this, right?

2020-09-17 09:25 UTC, Gluestick commented on Dockerfile
> +ENV DATOMIC_VERSION 1.0.6202.0
Ah, right. You could use `sed` to strip away the 4th digit from the version number when setting this value, so `bump.sh 1.0.6202.0` just works.

2020-09-17 10:44 UTC, Tim108 commented on Dockerfile
> +ENV DATOMIC_VERSION 1.0.6202.0
See newest commit 👌

2020-09-25 15:33 UTC, thumbnail approved these changes

2020-09-25 15:33 UTC, merged